site_name: filecloudapi-python
site_description: A Python library to connect to a Filecloud server
site_author: FileCloud

repo_url: https://github.com/codelathe/filecloudapi-python
edit_uri: https://github.com/codelathe/filecloudapi-python/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
